services:

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:alpine"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    networks:
      - backend
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  postgres:
    container_name: postgres
    image: "postgres:alpine"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  users:
    container_name: users
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 60s
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend
    environment:
      SERVICE_NAME: users
    volumes:
      - logs:/messenger-async/logs
    command: sh -c "sleep 10 && uvicorn app.users:app --host 0.0.0.0 --port 5000 --workers 2"

  auth:
    container_name: auth
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 60s
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend
    environment:
      SERVICE_NAME: auth
    volumes:
      - logs:/messenger-async/logs
    command: sh -c "sleep 10 && uvicorn app.auth:app --host 0.0.0.0 --port 5000 --workers 2"

  messages:
    container_name: messages
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 60s
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend
    environment:
      SERVICE_NAME: messages
    volumes:
      - logs:/messenger-async/logs
    command: sh -c "sleep 10 && uvicorn app.messages:app --host 0.0.0.0 --port 5000 --workers 2"


  sender:
    container_name: sender
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 60s
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - backend
    environment:
      SERVICE_NAME: sender
    volumes:
      - logs:/messenger-async/logs
    command: sh -c "sleep 10 && python ./app/sender.py"

  nginx:
    container_name: nginx
    build:
      context: .
      no_cache: true
      dockerfile: nginx/Dockerfile
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 3
        window: 60s
    depends_on:
      - auth
      - users
      - messages
    ports:
      - "5000:5000"
    networks:
      - backend
    command: sh -c "sleep 20 && nginx -g 'daemon off;'"


networks:
  backend:

volumes:
  logs:
  postgres:
  rabbitmq: