HOST = '0.0.0.0'
PORT = 5000
USER_EXISTS_ERROR = 'Username already exists.'
VALIDATION_ERROR = 'Validation error.'
NOT_AUTHORIZED = 'Not authorized.'
EXPIRED_TOKEN = 'Token expired.'
INVALID_TOKEN = 'Invalid token.'
LOGIN_SUCCESSFUL = 'Login successful.'
LOGOUT_SUCCESSFUL = 'Logout successful.'
INCORRECT_CREDS = 'Incorrect username or password.'
SUCCESSFUL = 'Operation successful.'
TOKEN_EXP_MINUTES = 60
MQ_EXCHANGE_NAME = 'EXCHANGE'
MQ_MSG_QUEUE_NAME = 'MSG_QUEUE'
MQ_LOGIN_QUEUE_NAME = 'LOGIN_QUEUE'
DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
SECRET_KEY = 'DO NOT USE IT ON PROD'
